name = "miata-registry"
compatibility_date = "2024-01-01"

[[routes]]
pattern = "miataregistry.com/store/car/*"
script = "image-read"

[[routes]]
pattern = "miataregistry.com/worker/api/images/*"
script = "image-write"

[env.production]
r2_buckets = [
  { binding = "IMAGES", bucket_name = "miata-registry-images" }
]