name: Deploy and Test

on:
    push:
        branches:
            - main
        paths:
            - '.dev.vars.example'
            - '.env.production.example'
            - '.github/workflows/deploy.yml'
            - 'src/db/**'
            - 'src/types/**'
            - 'src/utils/**'
            - 'src/worker/**'
            - 'package.json'
            - 'wrangler.toml'

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy
        steps:
            - name: Debugging - Print GitHub context
              env:
                  GITHUB_CONTEXT: ${{ toJSON(github) }}
              run: echo "$GITHUB_CONTEXT"

            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Build Worker
              run: npm run worker:build

            - name: Deploy to Cloudflare
              env:
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
              run: npm run worker:deploy

            - name: Wait for deployment
              run: sleep 90

            - name: Run Cypress tests
              id: cypress
              run: npx cypress run --config-file cypress.config.js --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
              continue-on-error: true

            - name: Send email notification on failure
              if: steps.cypress.outcome == 'failure'
              run: |
                  curl -X POST 'https://api.resend.com/emails' \
                  -H 'Authorization: Bearer ${{ secrets.RESEND_API_KEY }}' \
                  -H 'Content-Type: application/json' \
                  -d '{
                    "from": "Cypress Tests <support@miataregistry.com>",
                    "to": ["mattcongrove@gmail.com"],
                    "subject": "❌ Cypress Tests Failed",
                    "text": "Cypress tests failed in the deployment workflow."
                  }'

            - name: Exit with Cypress status
              if: steps.cypress.outcome == 'failure'
              run: exit 1
